-- MySQL Script generated by MySQL Workbench
-- Sat Jun  4 00:35:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdgro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdgro` ;

-- -----------------------------------------------------
-- Schema bdgro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdgro` DEFAULT CHARACTER SET utf8 ;
USE `bdgro` ;

-- -----------------------------------------------------
-- Table `bdgro`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgro`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `stock_quantity` INT NOT NULL,
  `delete` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgro`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgro`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `grade` VARCHAR(255) NOT NULL,
  `shadow` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgro`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgro`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customers_id` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_orders_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `bdgro`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgro`.`orderContent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgro`.`orderContent` (
  `orders_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_orderContent_products_idx` (`products_id` ASC),
  INDEX `fk_orderContent_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_orderContent_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `bdgro`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderContent_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `bdgro`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgro`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgro`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customers_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_transactions_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_transactions_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `bdgro`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgro`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgro`.`log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
